import { test, expect, store, weight, bloodPressure, readStore, addWeight, openSettings } from './fixtures.mjs'

test('add, reload, cancel, edit, and confirmed delete preserve unrelated data', async ({ page, app }) => {
  await app({ data: store([bloodPressure], { showBmi: false }) })
  await expect(page.locator('.chart-empty')).toBeVisible()
  await addWeight(page, { date: '2026-10-02', value: 82.8, note: 'First line\nSecond line' })
  let saved = await readStore(page)
  const record = saved.measurements.find(({ type }) => type === 'weight')
  expect(record.value).toBe(82.8)
  expect(record.note).toBe('First line\nSecond line')
  expect(new Date(record.timestamp).toLocaleDateString('en-CA', { timeZone: 'Europe/Berlin' })).toBe('2026-10-02')
  expect(saved.measurements).toContainEqual(bloodPressure)
  await page.reload()
  await expect(page.locator('.weight-hero strong')).toHaveText('82.8 kg')
  await page.locator('.entry-link').click()
  await expect(page.getByRole('spinbutton')).toHaveValue('82.8')
  await page.getByRole('spinbutton').fill('83.1')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await readStore(page)).toEqual(saved)
  await page.locator('.entry-link').click()
  await page.getByRole('spinbutton').fill('83.1')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  saved = await readStore(page)
  expect(saved.measurements.find(({ id }) => id === record.id).value).toBe(83.1)
  await page.locator('.entry-link').click()
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  expect(await readStore(page)).toEqual(saved)
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.locator('.weight-dashboard')).toBeVisible()
  expect((await readStore(page)).measurements).toEqual([bloodPressure])
  expect((await readStore(page)).profile).toEqual(saved.profile)
})

test('latest-weight hint stays empty and invalid values/dates cannot save', async ({ page, app }) => {
  await app({ data: store([weight('2026-10-01', 81)], { showBmi: false }) })
  const before = await readStore(page)
  await page.getByRole('button', { name: 'Add weight', exact: true }).click()
  const input = page.getByRole('spinbutton')
  await expect(input).toHaveValue('')
  await expect(input).toHaveAttribute('placeholder', '81.0')
  for (const invalid of ['', '0', '-1', '1000.1']) {
    await input.fill(invalid)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.locator('#entry-form')).toBeVisible()
    expect(await input.evaluate((element) => element.checkValidity())).toBe(false)
    expect(await readStore(page)).toEqual(before)
  }
  await input.fill('82')
  await page.getByLabel('Date', { exact: true }).fill('2026-10-04')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('#entry-form')).toBeVisible()
  // WebKit does not enforce date max natively; the application must reject it too.
  if (await page.getByLabel('Date', { exact: true }).evaluate((element) => element.checkValidity())) {
    await expect(page.getByRole('alert')).toHaveText('Measurements cannot be entered in the future.')
  }
  expect(await readStore(page)).toEqual(before)
  await page.getByLabel('Date', { exact: true }).fill('2026-10-01')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('A weight entry already exists for this date.')
  expect(await readStore(page)).toEqual(before)
})

test('backfilled records sort by date and editing cannot collide with another date', async ({ page, app }) => {
  await app({ data: store([weight('2026-09-01', 85)], { showBmi: false }) })
  await addWeight(page, { date: '2026-10-02', value: 81 })
  await addWeight(page, { date: '2026-09-15', value: 83 })
  await expect(page.locator('.entry time')).toHaveText(['2 Oct 2026', '15 Sept 2026', '1 Sept 2026'])
  await expect(page.locator('.entry em')).toHaveText(['-2.0 kg', '-2.0 kg'])
  await page.locator('.entry-link').first().click()
  await page.getByLabel('Date', { exact: true }).fill('2026-09-15')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.locator('.entry-link')).toHaveCount(3)
})

test('optional profile numbers remain absent when saving with BMI disabled', async ({ page, app }) => {
  await app({ data: store([weight('2026-10-01', 81)], { age: null, heightCm: null, showBmi: false }) })
  const before = await readStore(page)
  await openSettings(page)
  await page.getByRole('button', { name: /Profile Optional personal details/ }).click()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  expect(await readStore(page)).toEqual(before)
  await page.reload()
  expect(await readStore(page)).toEqual(before)
})

test('profile BMI settings cancel safely, validate height, save, and persist', async ({ page, app }) => {
  await app({ data: store([weight('2026-10-01', 81)], { age: null, heightCm: null, showBmi: false }) })
  await expect(page.locator('.bmi-summary')).toHaveCount(0)
  const before = await readStore(page)
  await openSettings(page)
  await page.getByRole('button', { name: /Profile Optional personal details/ }).click()
  await page.getByLabel('Show current BMI').check()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Enter your height to enable BMI.')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await readStore(page)).toEqual(before)
  await page.getByRole('button', { name: /Profile Optional personal details/ }).click()
  await page.getByRole('spinbutton', { name: /^Height/ }).fill('172')
  await page.getByLabel('Show current BMI').check()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.locator('.weight-bmi-value')).toHaveText('27.4')
  expect((await readStore(page)).profile.age).toBeNull()
  await page.reload()
  await expect(page.locator('.weight-bmi-value')).toHaveText('27.4')
})
