import { test, expect, store, weight, populatedStore, readStore } from './fixtures.mjs'

test('period selection updates chart, insight/reference date, and history but never the hero', async ({ page, app }) => {
  await app()
  const hero = await page.locator('.weight-hero').innerText()
  expect(hero).toContain('-3.0 kg')
  for (const [period, count, change, reference] of [
    ['3 months', 5, '-3.0 kg', 'Since 4 Jul 2026'],
    ['1 year', 9, '-7.0 kg', 'Since 5 Oct 2025'],
    ['All time', 10, '-9.0 kg', 'Since 15 Sept 2025'],
  ]) {
    await page.getByRole('button', { name: period, exact: true }).click()
    await expect(page.locator('.entry-link')).toHaveCount(count)
    await expect(page.locator('.chart-svg')).toHaveAttribute('aria-label', `Weight chart with ${count} measurements.`)
    await expect(page.locator('.summary article').first()).toHaveText(`${change}${reference}`)
    expect(await page.locator('.weight-hero').innerText()).toBe(hero)
  }
  await page.reload()
  await expect(page.getByRole('button', { name: '3 months', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('keyboard and touch chart selection expose the correct recorded values and notes', async ({ page, app }) => {
  await app()
  const slider = page.getByRole('slider', { name: 'Navigate weight measurements' })
  await slider.focus()
  await slider.press('Home')
  await expect(page.locator('.chart-tooltip')).toContainText('84.0 kg')
  await slider.press('ArrowRight')
  await expect(page.locator('.chart-tooltip')).toContainText('83.0 kg')
  await slider.press('End')
  await expect(page.locator('.chart-tooltip')).toContainText('81.0 kg')
  await expect(page.locator('.chart-tooltip')).toContainText('Current check-in')
  await slider.press('ArrowLeft')
  await expect(page.locator('.chart-tooltip')).toContainText('81.5 kg')
  await slider.scrollIntoViewIfNeeded()
  const box = await slider.boundingBox()
  await page.mouse.move(box.x + 5, box.y + box.height / 2)
  await expect(slider).toHaveAttribute('aria-valuenow', '0')
  // Keep inside the actual hit area: Firefox's SVG bounding box includes focus stroke.
  await page.touchscreen.tap(box.x + box.width - 5, box.y + box.height / 2)
  await expect(slider).toHaveAttribute('aria-valuenow', '4')
  const tooltip = await page.locator('.chart-tooltip').boundingBox()
  const dates = await page.locator('.x-end').boundingBox()
  expect(tooltip.y).toBeGreaterThan(dates.y + dates.height)
  await page.mouse.move(box.x + 5, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width - 5, box.y + box.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(slider).toHaveAttribute('aria-valuenow', '4')
})

test('average uses full history, preserves summaries, and resets only on reload', async ({ page, app }) => {
  await app()
  const before = await readStore(page)
  const summary = await page.locator('.summary').innerText()
  await page.getByRole('switch', { name: 'Average', exact: true }).check()
  await expect(page.locator('.weight-average-line')).toBeVisible()
  await expect(page.locator('.trend-line')).toHaveCount(0)
  const slider = page.getByRole('slider')
  await slider.focus()
  await slider.press('End')
  await expect(page.locator('.chart-tooltip')).toContainText('5-measurement average: 82.30 kg')
  await slider.press('Home')
  await expect(page.locator('.chart-tooltip')).toContainText('5-measurement average: 85.50 kg')
  expect(await page.locator('.summary').innerText()).toBe(summary)
  expect(await readStore(page)).toEqual(before)
  await page.getByRole('combobox', { name: 'Health areas' }).selectOption('bloodPressure')
  await page.getByRole('combobox', { name: 'Health areas' }).selectOption('weight')
  await expect(page.getByRole('switch', { name: 'Average', exact: true })).toBeChecked()
  await page.reload()
  await expect(page.getByRole('switch', { name: 'Average', exact: true })).not.toBeChecked()
})

for (const count of [0, 1, 4, 5, 6]) {
  test(`${count} measurements handle empty/single/average availability`, async ({ page, app }) => {
    await app({ data: store(Array.from({ length: count }, (_, i) => weight(`2026-09-${String(i + 1).padStart(2, '0')}`, 85 - i))) })
    await expect(page.locator('.entry-link')).toHaveCount(count)
    if (!count) await expect(page.locator('.chart-empty')).toBeVisible()
    if (count === 1) await expect(page.locator('.weight-selected-point')).toBeVisible()
    await page.getByRole('switch', { name: 'Average', exact: true }).check()
    if (count < 5) await expect(page.locator('#weight-average-unavailable')).toBeVisible()
    else if (count === 5) await expect(page.locator('.weight-average-point')).toBeVisible()
    else await expect(page.locator('.weight-average-line')).toBeVisible()
  })
}

test('no recent data does not imply a hero change; old and future records remain manageable', async ({ page, app }) => {
  await app({ data: store([weight('2025-09-15', 90), weight('2026-03-10', 85)]) })
  await expect(page.locator('.chart-empty')).toBeVisible()
  await expect(page.locator('.weight-hero strong')).toHaveText('85.0 kg')
  await expect(page.locator('.weight-hero p')).toHaveText('3 months')
  await page.getByRole('button', { name: 'All time', exact: true }).click()
  await expect(page.locator('.summary article').first()).toContainText('-5.0 kg')
})

test('existing future record is flagged and can be deleted', async ({ page, app }) => {
  await app({ data: store([weight('2026-10-04', 81)]) })
  await expect(page.locator('.future-record')).toBeVisible()
  await page.locator('.future-record').click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.locator('.entry-link')).toHaveCount(0)
})

test('BMI badge stays semantic when chart zones are toggled; info supports keyboard, touch, and dismissal', async ({ page, app }) => {
  await app()
  const badge = page.locator('.weight-bmi-value')
  await expect(badge).toHaveClass(/bmiAbove/)
  const color = await badge.evaluate((element) => getComputedStyle(element).backgroundColor)
  await page.getByRole('switch', { name: 'BMI zones' }).check()
  await expect(page.locator('.bmi-zone')).not.toHaveCount(0)
  expect(await badge.evaluate((element) => getComputedStyle(element).backgroundColor)).toBe(color)
  await page.getByRole('switch', { name: 'BMI zones' }).uncheck()
  expect(await badge.evaluate((element) => getComputedStyle(element).backgroundColor)).toBe(color)
  const info = page.locator('.weight-bmi-info summary')
  const content = page.getByRole('region', { name: 'BMI details' })
  await expect(content).toBeHidden()
  await info.focus()
  await info.press('Enter')
  await expect(content).toBeVisible()
  await expect(content).toContainText('Above WHO reference range')
  await expect(content).toContainText('25.0–29.9')
  await expect(content).toContainText('BMI is a screening estimate, not a medical diagnosis.')
  await info.press('Escape')
  await expect(content).toBeHidden()
  await expect(info).toBeFocused()
  await info.press('Space')
  await expect(content).toBeVisible()
  await info.press('Tab')
  await expect(content).toBeHidden()
  await info.tap()
  await expect(content).toBeVisible()
  const box = await content.boundingBox()
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(375)
  await page.locator('.weight-hero').tap()
  await expect(content).toBeHidden()
})

test('under-18 BMI remains neutral; older-adult context is available', async ({ page, app }) => {
  const data = populatedStore()
  data.profile.age = 17
  await app({ data })
  await expect(page.locator('.weight-bmi-value')).toHaveClass('weight-bmi-value')
  await expect(page.getByRole('switch', { name: 'BMI zones' })).toHaveCount(0)
  await page.locator('.weight-bmi-info summary').click()
  await expect(page.locator('.weight-bmi-popover')).toContainText('Adult ranges do not apply under age 18')
  await page.evaluate(() => {
    const data = JSON.parse(localStorage.getItem('health-tracker-data'))
    data.profile.age = 70
    localStorage.setItem('health-tracker-data', JSON.stringify(data))
  })
  await page.reload()
  await page.locator('.weight-bmi-info summary').click()
  await expect(page.locator('.weight-bmi-popover')).toContainText('After age 65')
})
